/*
 * Copyright 2017 Patrik Karlsson.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package se.trixon.nbmpc.ui;

import javax.swing.JButton;
import se.trixon.nbmpc.actions.TrackToggleAction;

/**
 *
 * @author Patrik Karlsson
 */
public class VolumePanel extends javax.swing.JPanel {

    /**
     * Creates new form VolumePanel
     */
    public VolumePanel() {
        initComponents();
        JButton b = new TrackToggleAction().getButton();
        b.setAlignmentX(0.5F);
        add(b);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jToggleButton1 = new javax.swing.JToggleButton();

        setOpaque(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider1.setAlignmentY(1.0F);
        add(jSlider1);

        jToggleButton1.setText(org.openide.util.NbBundle.getMessage(VolumePanel.class, "VolumePanel.jToggleButton1.text")); // NOI18N
        jToggleButton1.setAlignmentX(0.5F);
        add(jToggleButton1);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider jSlider1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
